CI-RT documentation
===================

The CI-RT tests changes of the PREEMPT_RT patch on different hardware
platforms with a defined test procedure. For a detailed description
please consider https://ci-rt.linutronix.de/RT-Test/about.jsp and
https://github.com/ci-rt/docs/blob/master/README.adoc[CI-RT
requirements and rules].


The CI-RT is split in several subprojects. They are shortly described
in the following.

Jenkins specific projects
-------------------------

The control instance uses jenkins to deploy the jobs on the different
defined slaves. The setup of the Jenkins master instance (and the
setup of the slaves) is described in
https://github.com/ci-rt/jenkins-cirt-libs/blob/master/README.adoc[README
of jenkins-cirt-libs].

https://github.com/ci-rt/test-description[test-description]::

	A textual description for the tests that needs to be
	executed. Additionally it contains the base Jenkinsfile which
	triggers only the CIRTscheduler, which is part of cirt Jenkins
	library. +
	For the explanation of the structure and the setup, please
	consider
	https://github.com/ci-rt/test-description/blob/master/README.adoc[README].


https://github.com/ci-rt/jenkins-cirt-libs[jenkins-cirt-libs]::

	The description for the single steps are defined in a Jenkins
	Pipeline shared library. +
	For setup, please consider
	https://github.com/ci-rt/jenkins-cirt-libs/blob/master/README.adoc[README].


https://github.com/ci-rt/libvirt-slave-plugin[libvirt-slave-plugin]::

	This repopository is a fork of
	https://github.com/jenkinsci/libvirt-slave-plugin with
	additional changes, that enables the selection of r4d as
	hypervisor to communicate with slaves via libvirt.


https://github.com/ci-rt/database[database]::

	The repository hosts the database scheme for the test results
	of the Jenkins tests. +
	For setup, please consider
	https://github.com/ci-rt/database/blob/master/README.adoc[README].

r4d and libvirt
---------------

The DUTs (or Jenkins slaves) are located in racks. To communicate with
real hardware in the same way you can communicate with virtual
machines, r4d was developed. Libvirt was adapted to support r4d.

r4d, libr4d and the patched libvirt are available as Debian packages
on http://debian.linutronix.de/tools mirror.


https://github.com/ci-rt/r4d[r4d]::

	For the communication abstraction for the targets located in
	racks, hypervisor r4d is used. +
	For setup, please consider
	https://github.com/ci-rt/r4d/blob/master/README.adoc[README].


https://github.com/ci-rt/libr4d[libr4d]::

	For the communication abstraction for the targets located in
	racks, hypervisor r4d is used. The C library libr4d provides
	helper functions to access and comunicate with the hypervisor
	r4d. +
	For setup, please consider
	https://github.com/ci-rt/libr4d/blob/master/README.adoc[README].


https://github.com/ci-rt/libvirt-debian[libvirt-debian]::

	This repo hosts the debianization of libvirt with additional
	changes, which make it possible to communicate with hypervisor
	r4d via libvirt. It is a clone of
	https://anonscm.debian.org/cgit/pkg-libvirt/libvirt.git/ and
	hosts the adapted debian/sid branch renamed as
	debian/jessie-backports and the adapted debian/stretch
	branch. +
	For setup, please consider
	https://github.com/ci-rt/libvirt-debian/blob/debian/jessie-backports/README.adoc[README].



Web specific projects
---------------------

The results of the tests can be visualized with a web application.

https://github.com/ci-rt/ci-web[ci-web]::

	The test results are displayed on a
	https://ci-rt.linutronix.de[web interface]. This git
	repository hosts the corresponding source code. You need the
	https://github.com/ci-rt/google-visualization-java[google-visualization-java]
	repository to build the web interface. Furthermore you need
	access to the https://github.com/ci-rt/database[database]
	storing the test results. +
	For setup, please consider
	https://github.com/ci-rt/ci-web/blob/master/README.adoc[README].


https://github.com/ci-rt/google-visualization-java[google-visualization-java]::

	This repo is a fork of
	https://github.com/google/google-visualization-java with
	additional changes, to make it possible to use postgresql data
	bases. +
	For setup, please consider
	https://github.com/ci-rt/ci-web/blob/master/README.adoc[ci-web
	README] and
	https://github.com/ci-rt/google-visualization-java/blob/master/README.adoc[google-visualization-java README].



DUT specific projects
---------------------

The DUTs or Jenkins slaves require several specific packages and also some extra
settings to be able to test booting the DUT via Jenkins. To be able to
reproducable rebuild the RFS, https://elbe-rfs.org/[E.L.B.E.] is used.

https://github.com/ci-rt/elbe-rfs[elbe-rfs]::

	This repo contains all required files to be able to build the RFS for a
	specific DUT. For more information about the tool which is used for
	building, please consider https://elbe-rfs.org/[E.L.B.E. website].



TESTBOX specific projects
-------------------------

The TESTBOX is a Banana Pi R1 router board expanded by a custom developed
shield. This results in a standardized adaption system to be able to handle not
standardized hardware in CI-RT and to run hardware assisted tests.

https://github.com/ci-rt/testbox-shield[testbox-shield]::

	This repo hosts all TESTBOX shield related drawings, layouts and
	schematics. It is a kicad version 5 based project. Please read the
	README before use.

https://github.com/ci-rt/testbox-rfs[testbox-rfs]::

	This repo contains the http://elbe-rfs.org/[E.L.B.E] recipe to build a
	root file system for the TESTBOX. For more information about the tool
	E.L.B.E. which is used for building, please consider
	https://elbe-rfs.org/[E.L.B.E. website].
